//definición de variables
let num1,num2, resultado

//asignacion de valores a variables
num1 = 5
num2 = 15

//suma
resultado= num1 + num2
//imprimir resultado
console.log(`Es resultado de la suma es: ${resultado}`)

//resta
resultado = num1 - num2
console.log(`El resultado de la resta es: ${resultado}`)

//multiplicación
resultado = num1 * num2
console.log(`El resultado de la multiplicación es: ${resultado}`)

//división
resultado = num1 / num2
console.log(`El resultado de la division es ${resultado}`)

//Modulo
resultado = num1 % num2
console.log(`El resultado de el modulo es: ${resultado}`)

//Exponenciación
resultado = num1 ** num2
console.log(`El resultado de la exponenciación es: ${resultado}`)
